import React, { useState, useEffect } from 'react';
import axios from 'axios';
import { Link, useNavigate } from 'react-router-dom';
import Cookies from 'js-cookie';
import { motion } from 'framer-motion';
import { Search, Calendar, User, ArrowRight, Tag, LogOut, LayoutDashboard } from 'lucide-react';

const Home = () => {
  const [blogs, setBlogs] = useState([]);
  const [categories, setCategories] = useState([]);
  const [activeCategory, setActiveCategory] = useState('All');
  const [loading, setLoading] = useState(true);
  const [user, setUser] = useState(null);
  const navigate = useNavigate();

  useEffect(() => {
    const username = Cookies.get('username');
    const role = Cookies.get('userRole');
    if (username) {
      setUser({ username, role });
    }

    const fetchBlogs = async () => {
      try {
        const { data } = await axios.get('/api/blogs');
        setBlogs(data);

        // Extract unique categories safely
        const allCategories = data.flatMap(b => b.categories || []);
        const cats = ['All', ...new Set(allCategories)];
        setCategories(cats);
        setLoading(false);
      } catch (err) {
        console.error(err);
        setLoading(false);
      }
    };
    fetchBlogs();
  }, []);

  const filteredBlogs = activeCategory === 'All'
    ? blogs
    : blogs.filter(b => b.categories.includes(activeCategory));

  return (
    <div className="home-container" style={{ position: 'relative' }}>
      {/* Hero Section */}
      <header className="hero container animate-fade" style={{ paddingTop: '150px', paddingBottom: '80px', textAlign: 'center' }}>
        <motion.div
          initial={{ opacity: 0, scale: 0.9 }}
          animate={{ opacity: 1, scale: 1 }}
          transition={{ duration: 0.8, ease: 'easeOut' }}
        >
          <span style={{ fontSize: '0.9rem', color: 'var(--primary)', fontWeight: '700', textTransform: 'uppercase', letterSpacing: '0.2em', marginBottom: '15px', display: 'block' }}>Autonomous Blog Agent</span>
          <h1
            className="text-gradient"
            style={{ fontSize: '5rem', marginBottom: '25px', lineHeight: '1', fontWeight: '900' }}
          >
            Insights from <br /> the Future.
          </h1>
          <p style={{ color: 'var(--text-muted)', fontSize: '1.2rem', maxWidth: '650px', margin: '0 auto', lineHeight: '1.6' }}>
            A curated flow of cutting-edge technology, AI evolution, and startup wisdom, generated by intelligence and refined by humans.
          </p>
        </motion.div>
      </header>

      {/* Category Filter */}
      <section className="container" style={{ marginBottom: '60px' }}>
        <div style={{ display: 'flex', gap: '12px', overflowX: 'auto', whiteSpace: 'nowrap', padding: '10px 0' }}>
          {categories.map(cat => (
            <button
              key={cat}
              onClick={() => setActiveCategory(cat)}
              style={{
                background: activeCategory === cat ? 'var(--primary)' : 'var(--glass)',
                padding: '10px 24px',
                borderRadius: '14px',
                color: 'white',
                fontWeight: '600',
                border: '1px solid',
                borderColor: activeCategory === cat ? 'var(--primary)' : 'var(--glass-border)',
                transition: 'all 0.3s ease',
                boxShadow: activeCategory === cat ? '0 10px 20px rgba(139, 92, 246, 0.3)' : 'none'
              }}
            >
              {cat}
            </button>
          ))}
        </div>
      </section>

      {/* Blog Grid */}
      <main className="container blog-grid" style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(380px, 1fr))', gap: '40px', paddingBottom: '120px' }}>
        {loading ? (
          <div style={{ gridColumn: '1 / -1', textAlign: 'center', padding: '100px 0' }}>
            <motion.div animate={{ rotate: 360 }} transition={{ repeat: Infinity, duration: 1, ease: 'linear' }} style={{ width: '40px', height: '40px', border: '4px solid var(--primary)', borderTopColor: 'transparent', borderRadius: '50%', margin: '0 auto' }} />
          </div>
        ) : filteredBlogs.length > 0 ? (
          filteredBlogs.map((blog, idx) => (
            <motion.article
              key={blog._id}
              className="glass"
              style={{ overflow: 'hidden', display: 'flex', flexDirection: 'column', border: '1px solid var(--glass-border)' }}
              initial={{ opacity: 0, y: 30 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: idx * 0.05 }}
              whileHover={{ y: -10, borderColor: 'rgba(255,255,255,0.2)', boxShadow: '0 30px 60px rgba(0,0,0,0.4)' }}
            >
              {blog.bannerImage && (
                <div style={{ height: '240px', width: '100%', overflow: 'hidden', position: 'relative' }}>
                  <img src={blog.bannerImage} alt={blog.title} style={{ width: '100%', height: '100%', objectFit: 'cover', transition: 'transform 0.5s ease' }} />
                  <div style={{ position: 'absolute', bottom: '15px', left: '15px' }}>
                    <span style={{ fontSize: '0.75rem', padding: '6px 12px', background: 'rgba(15, 23, 42, 0.8)', backdropFilter: 'blur(10px)', borderRadius: '8px', color: 'white', fontWeight: 'bold', border: '1px solid var(--glass-border)' }}>
                      {blog.categories?.[0] || 'Tech'}
                    </span>
                  </div>
                </div>
              )}
              <div style={{ padding: '30px', flex: 1, display: 'flex', flexDirection: 'column' }}>
                <h2 style={{ fontSize: '1.6rem', marginBottom: '15px', lineHeight: '1.3', fontWeight: '700' }}>{blog.title || 'Untitled'}</h2>
                <p style={{ color: 'var(--text-muted)', fontSize: '1rem', marginBottom: '25px', display: '-webkit-box', WebkitLineClamp: '3', WebkitBoxOrient: 'vertical', overflow: 'hidden', lineHeight: '1.6' }}>
                  {blog.summary || (blog.content ? blog.content.substring(0, 150) + '...' : 'No content available')}
                </p>
                <div style={{ marginTop: 'auto', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                  <div style={{ display: 'flex', gap: '20px', color: 'var(--text-muted)', fontSize: '0.85rem' }}>
                    <span style={{ display: 'flex', alignItems: 'center', gap: '6px' }}><Calendar size={16} /> {new Date(blog.date).toLocaleDateString()}</span>
                  </div>
                  <Link to={`/blog/${blog.slug}`} style={{ color: 'var(--primary)', fontWeight: '700', display: 'flex', alignItems: 'center', gap: '6px', fontSize: '1rem' }}>
                    Dive In <ArrowRight size={18} />
                  </Link>
                </div>
              </div>
            </motion.article>
          ))
        ) : (
          <div style={{ gridColumn: '1 / -1', textAlign: 'center', padding: '100px 0', opacity: 0.5 }}>
            <p style={{ fontSize: '1.2rem' }}>No stories found in this category.</p>
          </div>
        )}
      </main>
    </div>
  );
};

export default Home;
