import React, { useState, useEffect } from 'react';
import api from '../utils/api';
import { Link, useNavigate } from 'react-router-dom';
import Cookies from 'js-cookie';
import { motion, AnimatePresence } from 'framer-motion';
import { Calendar, ArrowRight, Filter, X, Layers, ChevronRight } from 'lucide-react';

const Home = () => {
  const [blogs, setBlogs] = useState([]);
  const [categories, setCategories] = useState([]);
  const [activeCategory, setActiveCategory] = useState('All');
  const [loading, setLoading] = useState(true);
  const [user, setUser] = useState(null);
  const [sidebarOpen, setSidebarOpen] = useState(false);
  const navigate = useNavigate();

  useEffect(() => {
    const username = Cookies.get('username');
    const role = Cookies.get('userRole');
    if (username) {
      setUser({ username, role });
    }

    const fetchBlogs = async () => {
      try {
        const { data } = await api.get('/blogs');
        setBlogs(data);

        // Extract unique categories safely
        const allCategories = data.flatMap(b =>
          (b.categories || []).map(c => c.toLowerCase())
        );

        const cats = ['All', ...new Set(allCategories)];
        setCategories(cats);
        setLoading(false);
      } catch (err) {
        console.error(err);
        setLoading(false);
      }
    };
    fetchBlogs();
  }, []);

  const filteredBlogs = activeCategory === 'All'
    ? blogs
    : blogs.filter(b => b.categories.includes(activeCategory));

  const handleCategoryClick = (cat) => {
    setActiveCategory(cat);
    // On mobile, close sidebar after selection
    if (window.innerWidth < 768) {
      setSidebarOpen(false);
    }
  };

  return (
    <div className="home-container" style={{ position: 'relative' }}>
      {/* Hero Section */}
      <header className="hero container animate-fade" style={{ paddingTop: '120px', paddingBottom: '50px', textAlign: 'center' }}>
        <motion.div
          initial={{ opacity: 0, scale: 0.9 }}
          animate={{ opacity: 1, scale: 1 }}
          transition={{ duration: 0.8, ease: 'easeOut' }}
        >
          <span style={{ fontSize: '0.85rem', color: 'var(--primary)', fontWeight: '700', textTransform: 'uppercase', letterSpacing: '0.2em', marginBottom: '12px', display: 'block' }}>Autonomous Blog Agent</span>
          <h1
            className="text-gradient"
            style={{ fontSize: 'clamp(2.2rem, 7vw, 5rem)', marginBottom: '20px', lineHeight: '1.05', fontWeight: '900' }}
          >
            Insights from <br /> the Future.
          </h1>
          <p style={{ color: 'var(--text-muted)', fontSize: 'clamp(0.95rem, 2.5vw, 1.2rem)', maxWidth: '650px', margin: '0 auto', lineHeight: '1.6', padding: '0 0.5rem' }}>
            A curated flow of cutting-edge technology, AI evolution, and startup wisdom, generated by intelligence and refined by humans.
          </p>
        </motion.div>
      </header>

      {/* Floating Sidebar Toggle Button */}
      <motion.button
        onClick={() => setSidebarOpen(!sidebarOpen)}
        whileHover={{ scale: 1.05 }}
        whileTap={{ scale: 0.95 }}
        style={{
          position: 'fixed',
          right: '30px',
          bottom: '30px',
          left: 'auto',
          top: 'auto',
          transform: 'none',
          zIndex: 1100,
          width: '44px',
          height: '44px',
          borderRadius: '12px',
          background: 'linear-gradient(135deg, var(--primary), var(--secondary))',
          border: 'none',
          color: 'white',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          cursor: 'pointer',
          boxShadow: '0 4px 20px rgba(139, 92, 246, 0.4)',
          transition: 'left 0.35s cubic-bezier(0.4, 0, 0.2, 1)',
        }}
        aria-label={sidebarOpen ? 'Close categories' : 'Open categories'}
      >
        {sidebarOpen ? <X size={20} /> : <Filter size={20} />}
      </motion.button>

      {/* Sidebar Overlay (mobile) */}
      <AnimatePresence>
        {sidebarOpen && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            transition={{ duration: 0.2 }}
            onClick={() => setSidebarOpen(false)}
            style={{
              position: 'fixed',
              inset: 0,
              background: 'rgba(0, 0, 0, 0.4)',
              backdropFilter: 'blur(4px)',
              zIndex: 1049,
            }}
          />
        )}
      </AnimatePresence>

      {/* Categories Sidebar */}
      <AnimatePresence>
        {sidebarOpen && (
          <motion.aside
            initial={{ x: '-100%', opacity: 0 }}
            animate={{ x: 0, opacity: 1 }}
            exit={{ x: '-100%', opacity: 0 }}
            transition={{ type: 'spring', damping: 28, stiffness: 300 }}
            style={{
              position: 'fixed',
              top: 0,
              left: 0,
              width: '280px',
              height: '100vh',
              background: 'rgba(12, 10, 30, 0.95)',
              backdropFilter: 'blur(24px)',
              borderRight: '1px solid var(--glass-border)',
              zIndex: 1050,
              display: 'flex',
              flexDirection: 'column',
              boxShadow: '20px 0 60px rgba(0, 0, 0, 0.5)',
              overflowY: 'auto',
            }}
          >
            {/* Sidebar Header */}
            <div style={{
              padding: '30px 24px 20px',
              borderBottom: '1px solid var(--glass-border)',
            }}>
              <div style={{
                display: 'flex',
                alignItems: 'center',
                gap: '10px',
                marginBottom: '8px'
              }}>
                <div style={{
                  width: '36px',
                  height: '36px',
                  borderRadius: '10px',
                  background: 'linear-gradient(135deg, var(--primary), var(--secondary))',
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'center',
                  boxShadow: '0 4px 12px rgba(139, 92, 246, 0.3)'
                }}>
                  <Layers size={18} color="white" />
                </div>
                <h3 style={{
                  fontFamily: 'var(--font-accent)',
                  fontSize: '1.2rem',
                  fontWeight: '700',
                  margin: 0,
                }}>Categories</h3>
              </div>
              <p style={{
                color: 'var(--text-muted)',
                fontSize: '0.8rem',
                margin: 0,
              }}>
                {filteredBlogs.length} {filteredBlogs.length === 1 ? 'post' : 'posts'} in <span style={{ color: 'var(--primary)', fontWeight: '600' }}>{activeCategory}</span>
              </p>
            </div>

            {/* Category List */}
            <div style={{
              padding: '16px',
              display: 'flex',
              flexDirection: 'column',
              gap: '6px',
              flex: 1,
            }}>
              {categories.map((cat, index) => {
                const isActive = activeCategory === cat;
                const count = cat === 'All'
                  ? blogs.length
                  : blogs.filter(b => b.categories.includes(cat)).length;

                return (
                  <motion.button
                    key={cat}
                    initial={{ opacity: 0, x: -20 }}
                    animate={{ opacity: 1, x: 0 }}
                    transition={{ delay: index * 0.03 }}
                    onClick={() => handleCategoryClick(cat)}
                    style={{
                      display: 'flex',
                      alignItems: 'center',
                      justifyContent: 'space-between',
                      padding: '12px 16px',
                      borderRadius: '12px',
                      border: 'none',
                      cursor: 'pointer',
                      transition: 'all 0.25s ease',
                      background: isActive
                        ? 'linear-gradient(135deg, rgba(139, 92, 246, 0.2), rgba(236, 72, 153, 0.1))'
                        : 'transparent',
                      borderLeft: isActive ? '3px solid var(--primary)' : '3px solid transparent',
                      color: isActive ? 'white' : 'var(--text-muted)',
                    }}
                    whileHover={{
                      background: isActive
                        ? 'linear-gradient(135deg, rgba(139, 92, 246, 0.25), rgba(236, 72, 153, 0.15))'
                        : 'rgba(255, 255, 255, 0.04)',
                      color: 'white',
                    }}
                  >
                    <span style={{
                      display: 'flex',
                      alignItems: 'center',
                      gap: '10px',
                      fontSize: '0.9rem',
                      fontWeight: isActive ? '700' : '500',
                      textTransform: 'capitalize',
                    }}>
                      {isActive && <ChevronRight size={14} style={{ color: 'var(--primary)' }} />}
                      {cat}
                    </span>
                    <span style={{
                      fontSize: '0.75rem',
                      fontWeight: '600',
                      padding: '2px 8px',
                      borderRadius: '8px',
                      background: isActive
                        ? 'rgba(139, 92, 246, 0.3)'
                        : 'rgba(255, 255, 255, 0.05)',
                      color: isActive ? 'var(--primary)' : 'var(--text-muted)',
                      minWidth: '28px',
                      textAlign: 'center',
                    }}>
                      {count}
                    </span>
                  </motion.button>
                );
              })}
            </div>

            {/* Sidebar Footer */}
            <div style={{
              padding: '20px 24px',
              borderTop: '1px solid var(--glass-border)',
            }}>
              <p style={{
                fontSize: '0.75rem',
                color: 'var(--text-muted)',
                textAlign: 'center',
                opacity: 0.6,
              }}>
                Press the filter button to toggle
              </p>
            </div>
          </motion.aside>
        )}
      </AnimatePresence>

      {/* Active Category Indicator (when sidebar is closed) */}
      {!sidebarOpen && activeCategory !== 'All' && (
        <motion.div
          initial={{ opacity: 0, y: -10 }}
          animate={{ opacity: 1, y: 0 }}
          className="container"
          style={{ marginBottom: '20px', display: 'flex', alignItems: 'center', gap: '12px' }}
        >
          <span style={{
            fontSize: '0.85rem',
            color: 'var(--text-muted)',
          }}>Filtering by:</span>
          <span style={{
            padding: '6px 16px',
            borderRadius: '20px',
            fontSize: '0.85rem',
            fontWeight: '600',
            background: 'linear-gradient(135deg, rgba(139, 92, 246, 0.15), rgba(236, 72, 153, 0.08))',
            border: '1px solid rgba(139, 92, 246, 0.25)',
            color: 'var(--primary)',
            textTransform: 'capitalize',
            display: 'flex',
            alignItems: 'center',
            gap: '6px',
          }}>
            {activeCategory}
            <button
              onClick={() => setActiveCategory('All')}
              style={{
                background: 'none',
                border: 'none',
                color: 'var(--text-muted)',
                cursor: 'pointer',
                padding: 0,
                display: 'flex',
                alignItems: 'center',
              }}
            >
              <X size={14} />
            </button>
          </span>
          <span style={{ fontSize: '0.8rem', color: 'var(--text-muted)' }}>
            ({filteredBlogs.length} {filteredBlogs.length === 1 ? 'post' : 'posts'})
          </span>
        </motion.div>
      )}

      {/* Blog Grid */}
      <main className="container blog-grid" style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(min(380px, 100%), 1fr))', gap: '30px', paddingBottom: '80px' }}>
        {loading ? (
          <div style={{ gridColumn: '1 / -1', textAlign: 'center', padding: '100px 0' }}>
            <motion.div animate={{ rotate: 360 }} transition={{ repeat: Infinity, duration: 1, ease: 'linear' }} style={{ width: '40px', height: '40px', border: '4px solid var(--primary)', borderTopColor: 'transparent', borderRadius: '50%', margin: '0 auto' }} />
          </div>
        ) : filteredBlogs.length > 0 ? (
          filteredBlogs.map((blog, idx) => (
            <motion.article
              key={blog._id}
              className="glass"
              style={{ overflow: 'hidden', display: 'flex', flexDirection: 'column', border: '1px solid var(--glass-border)' }}
              initial={{ opacity: 0, y: 30 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: idx * 0.05 }}
              whileHover={{ y: -10, borderColor: 'rgba(255,255,255,0.2)', boxShadow: '0 30px 60px rgba(0,0,0,0.4)' }}
            >
              {blog.bannerImage && (
                <div style={{ height: '240px', width: '100%', overflow: 'hidden', position: 'relative' }}>
                  <img src={blog.bannerImage} alt={blog.title} style={{ width: '100%', height: '100%', objectFit: 'cover', transition: 'transform 0.5s ease' }} />
                  <div style={{ position: 'absolute', bottom: '15px', left: '15px' }}>
                    <span style={{ fontSize: '0.75rem', padding: '6px 12px', background: 'rgba(15, 23, 42, 0.8)', backdropFilter: 'blur(10px)', borderRadius: '8px', color: 'white', fontWeight: 'bold', border: '1px solid var(--glass-border)' }}>
                      {blog.categories?.[0] || 'Tech'}
                    </span>
                  </div>
                </div>
              )}
              <div style={{ padding: '30px', flex: 1, display: 'flex', flexDirection: 'column' }}>
                <h2 style={{ fontSize: '1.6rem', marginBottom: '15px', lineHeight: '1.3', fontWeight: '700' }}>{blog.title || 'Untitled'}</h2>
                <p style={{ color: 'var(--text-muted)', fontSize: '1rem', marginBottom: '25px', display: '-webkit-box', WebkitLineClamp: '3', WebkitBoxOrient: 'vertical', overflow: 'hidden', lineHeight: '1.6' }}>
                  {blog.summary || (blog.content ? blog.content.substring(0, 150) + '...' : 'No content available')}
                </p>
                <div style={{ marginTop: 'auto', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                  <div style={{ display: 'flex', gap: '20px', color: 'var(--text-muted)', fontSize: '0.85rem' }}>
                    <span style={{ display: 'flex', alignItems: 'center', gap: '6px' }}><Calendar size={16} /> {new Date(blog.date).toLocaleDateString()}</span>
                  </div>
                  <Link to={`/blog/${blog.slug}`} style={{ color: 'var(--primary)', fontWeight: '700', display: 'flex', alignItems: 'center', gap: '6px', fontSize: '1rem' }}>
                    Dive In <ArrowRight size={18} />
                  </Link>
                </div>
              </div>
            </motion.article>
          ))
        ) : (
          <div style={{ gridColumn: '1 / -1', textAlign: 'center', padding: '100px 0', opacity: 0.5 }}>
            <p style={{ fontSize: '1.2rem' }}>No stories found in this category.</p>
          </div>
        )}
      </main>
    </div>
  );
};

export default Home;

